### PR TITLE
Multiple TVs on the same Bridge

### PR DESCRIPTION
**Pull request by tavicu**
# This branch is under development. Install it only if you know what you are doing!

Branch is to test the new functionality for register the TV as external accessories. This will allow to have multiple TV's on the same bridge.

- Stop homebridge
- Get this branch as plugin with `npm install -g --unsafe-perm git://github.com/tavicu/homebridge-samsung-tizen.git#external-accessory`
- Start homebridge
- Add the accessories to Home app

### CODE REVIEW

**Comment by mhartung87** [comment]
Hello, 

Is this up and working? What do I need to do to get multiple samsung tvs on one bridge?

**Comment by tavicu** [comment]
> Hello,
> 
> Is this up and working? What do I need to do to get multiple samsung tvs on one bridge?

You can get multiple tvs with the actual version but you will be able to control only one from Remote Control Widget.

With this branch you will be able to control all but it's still in development!

**Comment by mhartung87** [comment]
Ok sounds good. Appreciate all your hard work. What code should I be using i have tried all different kind of options. What do be able to have switches and inputs

    "platforms": [
        {
            "platform": "SamsungTizen",
            "devices": [
                {
                    "name": "Bedroom TV",
                    "ip": "10.20.30.40",
                    "mac": "A0:B1:C2:D3:E4:F5",
                    "switches": [
                        {"name": "Mute",      "mute": true},
                        {"name": "Sleep",     "sleep": 60},
                        {"name": "Channel",   "channel": 13},
                        {"name": "Command 1", "command": "KEY_VOLUP"},
                        {"name": "Command 2", "command": "KEY_VOLUP*5"},
                        {"name": "Command 3", "command": ["KEY_VOLUP", "KEY_VOLDOWN"]},
                        {"name": "Command 4", "command": ["KEY_VOLUP*5", "KEY_VOLDOWN*3"]},
                        {"name": "All", "sleep": 60, "mute": true, "command": ["KEY_VOLUP", "KEY_VOLDOWN"], "channel": 13}
                    ]
                }
            ]
        }
    ]
}

**Comment by tavicu** [comment]
```
"platforms": [{
    "platform": "SamsungTizen",
    "devices": [{
        "name": "Bedroom TV",
        "ip": "10.20.30.40",
        "mac": "A0:B1:C2:D3:E4:F5",
        "inputs": [
            ...
        ],
        "switches": [
            ...
        ]
    }]
}]
```

Or if you want to have the same inputs on all devices you can set them like this:
```
"platforms": [{
    "platform": "SamsungTizen",
    "inputs": [
        ...
    ],    
    "devices": [{
        "name": "Bedroom TV",
        "ip": "10.20.30.40",
        "mac": "A0:B1:C2:D3:E4:F5",
        "switches": [
            ...
        ]
    }]
}]
```

Works for switches too
```
"platforms": [{
    "platform": "SamsungTizen",
    "inputs": [
        ...
    ],    
    "switches": [
        ...
    ],
    "devices": [{
        "name": "Bedroom TV",
        "ip": "10.20.30.40",
        "mac": "A0:B1:C2:D3:E4:F5"
    }]
}]
```

**Comment by mhartung87** [comment]
Ok where would I put the second TV at? If i wanted to code it as separate TVs and each tv has its own switches and inputs?

**Comment by tavicu** [comment]
```
"platforms": [{
    "platform": "SamsungTizen",
    "devices": [
        {
            "name": "Bedroom TV",
            "ip": "10.20.30.40",
            "mac": "A0:B1:C2:D3:E4:F5",
            "inputs": [
                ...
            ],
            "switches": [
                ...
            ]
        },
        {
            "name": "Living Room TV",
            "ip": "10.20.30.40",
            "mac": "A0:B1:C2:D3:E4:F5",
            "inputs": [
                ...
            ],
            "switches": [
                ...
            ]
        }        
    ]
}]
```

**Comment by mhartung87** [comment]
Awesome thank You! I will give it a shot

**Comment by mhartung87** [comment]
Getting error

Error: Parse error on line 82:
...}				]			}		]	}]
-------------------^
Expecting '}', ',', got 'EOF'

**Comment by tavicu** [comment]
Be careful at the parentheses! It's an error on your config file!

**Comment by mhartung87** [comment]
i used your exact code. it errors on the last line }]

**Comment by tavicu** [comment]
> i used your exact code. it errors on the last line }]

That code it's only a part that should be put under `platforms`. https://github.com/tavicu/homebridge-samsung-tizen/blob/master/config-sample.json

**Comment by mhartung87** [comment]
Thanks! i am not not what I did but i got it to work :)

**Comment by homohurre123** [comment]
Hmm I would like to make this work too. Do I Understand correctly that I can then also have multiple TVs from other Plugins? I have Harmony Plugin which supports this alongside the Tizen Plugin right now which works good. But If I try to Add Broadlink-rm-tv to it the third one whatever it is tizen or Broadlink only one remote shows up. 
https://github.com/AlexanderBabel/homebridge-broadlink-rm
https://github.com/nicoduj/homebridge-harmony

 {
      "platform" : "SamsungTizen",
      "inputs" : [
        {
          "name" : "Plex",
          "type" : "app",
          "value" : "3201512006963"
        },
        {
          "name" : "Spotify",
          "type" : "app",
          "value" : "3201606009684"
        },
        {
          "name" : "PC",
          "type" : "command",
          "value" : [
            "KEY_SOURCE",
            "KEY_LEFT*3",
            "KEY_RIGHT",
            "KEY_ENTER"
          ]
        },
        {
          "name" : "Netflix",
          "type" : "app",
          "value" : "11101200001"
        },
        {
          "name" : "Youtube",
          "type" : "app",
          "value" : "111299001912"
        }
      ],
      "devices" : [
        {
          "name" : " TV",
          "ip" : "XXX.XXX.0.XXX",
          "mac" : "XX:XX:XX:XX:XX:XX"
        }
      ]
    },

**Comment by tavicu** [comment]
This plugin has nothing to do with other plugins! So, installing this branch will allow you to add multiple Samsung TVs and control them in Control Center (only the tvs from this plugin).

**Comment by homohurre123** [comment]
Hmm Okay Was just wondering because the TV as external Accesorry thing on the harmony plugin gave me the possibility to run the tizen remote alongside the harmony remote.  
Do you think this might be possible in the future?

**Comment by tavicu** [comment]
> Okay Was just wondering because the TV as external Accesorry thing on the harmony plugin gave me the possibility to run the tizen remote alongside the harmony remote.
> Do you think this might be possible in the future?

Looks like you did not understood me!

You can have 100 TV's on my plugin and all 100 will work in Control Center.
If you will have two more plugins that are not configured as external accessories, those two will have a conflict and show only one!

That has to do with those two plugins because they need to change the code and treat every tv as external accessory! :)

**Comment by homohurre123** [comment]
Yeah I got that. The Way I understood it so far is just that if I have one plugin not configured as external Accessory and two others with it all of them should work. at least I thought so because I could  have two TVs right now in control center remote with one being not an external accessory

**Comment by tavicu** [comment]
You are correct! If you have one plugin (with one TV) that was not configured to work as external accessory and two others that are configured, it should work! 

As soon as you will add the second TV to the plugin that don't support external accessory, that TV will not show in Control Center!

Also, don't forget that my plugin with the current version it's not working as external accessory! You will need to follow the steps from the first comment to install this version.

I want to create a better readme before i release it since all the people will have to add the TV as a new accessory from the Home App.

And another downsize will be for people that use config-ui-x (https://www.npmjs.com/package/homebridge-config-ui-x) to control accessories! Since they will be external accessories, they will not appear in the interface.

**Comment by homohurre123** [comment]
Okay I installed it the way you said. Now for some reason the TV disappeared from Home entirely. Do I have to add it manually? 
The Log shows "Initializing SamsungTizen platform..."
And then nothing ...

**Comment by mhartung87** [comment]
tavicu - this supports any TV with tizen correct? Is there a way you can check to see if your tv has Tizen?

**Comment by tavicu** [comment]
> Okay I installed it the way you said. Now for some reason the TV disappeared from Home entirely. Do I have to add it manually?

It should appear a message in console 'bla bla bla: pin xxx-xxx-xxx bla bla bla'
You need to add it. Go to add accessory.

> tavicu - this supports any TV with tizen correct? Is there a way you can check to see if your tv has Tizen?

Most of the TV's with Tizen! There are some that work with a PIN instead of token. Those are not compatible.
You can find some closed issues where you can check if tv is compatible.

**Comment by mhartung87** [comment]
Ok!  i turned the TV on but i cant find  General - External Device Manager - Device Connection Manager - Device List and i never see a pop up to allow.

**Comment by homohurre123** [comment]
I Don't get it I tried several things but I don't get it to work. The console doesn't show anything either. Also I have to first uninstall the plugin in order to install your command above. If I Don't uninstall it I get permission errors . Something weird I noticed is if I succeed installing the command I get plugin version 3.1.0 not 3.1.4 may it be related?

**Comment by tavicu** [comment]
It’s ok! If you have 3.1.0 it’s this version with external accessories!

**Comment by homohurre123** [comment]
Well then I have no idea... I guess I will wait for the final version

**Comment by tavicu** [comment]
I am ready to release this version and i have updated the Wiki section with all the informations i could think of :) 

What do you guys think? Some improvements to the wiki?
https://github.com/tavicu/homebridge-samsung-tizen/wiki

**Comment by mhartung87** [comment]
I think it looks good. Now, It seems like the tv's and everything added them selfs to home app? Should i remove them and readd the accessory?

**Comment by tavicu** [comment]
Nope :) 

With the v4 you will have! But it’s not launched yet! This weekend i will do it!

**Comment by mhartung87** [comment]
Ok sounds good! I appreciate all your hard work with this. So I will have have to readd the accessories? Its so strange i remove the config file it removes the devices and i re add everything comes back.

**Pull request merged**
