### PR TITLE
Create Frame Method

### PR DESCRIPTION
**Pull request by tavicu**
This is an under development branch for Frame TVs!

### CODE REVIEW

**Comment by tavicu** [comment]
Since i don't have a Frame TV most of the development i will do it blank. It will help me if more users are willing to follow some instructions i ask in order to make sure everything it's ok and to have a beta version of this feature.

Starting next week i will work on it. So, until then if anyone want's to help me and make communication easier i have started a Discord Server (channel or whatever is calling, i'm not using Discord) and you can join https://discord.gg/zRWXJMq

@JordanPatterson, @codyc1515

**Comment by tavicu** [comment]
I have started by creating a local websocket server which will respond like TV.
Also i have created 4 scripts that someone with a Frame TV needs to run (@codyc1515 maybe 👍)

Scripts are here: https://gist.github.com/tavicu/5877d6c30a9166892e871b1cdae2b444

- Script 1 -> Turn the TV ON then run the script `node script1.js TV_IP`
- Script 2 -> Turn the TV OFF then run the script `node script2.js TV_IP`
- Script 3 -> Make sure TV is OFF then run the script `node script3.js TV_IP`
- Script 4 -> Make sure TV is ON then run the script and follow the request from console (turning on and off the tv from remote control) `node script4.js TV_IP`

Once i have the console output of these 4 scripts i can map my local server like a frame tv.

**Comment by JordanPatterson** [comment]
I have no problem running the scripts if you have provide a touch of assistance. Do these need to be run in the hombridge environment or will any terminal on the local network work?

**Comment by tavicu** [comment]
Any terminal from the same network with TV.

First create a folder where you store the 4 files, then install a npm plugin with `npm install ws`, then run the scripts :)

**Comment by JordanPatterson** [comment]
Ok Codyc1515 might beat me tot he punch but as soon as I get home from work I will get you the output.

**Comment by JordanPatterson** [comment]
When you say that the TV is off or on do you mean fully off and on or art mode and normal operation?

**Comment by tavicu** [comment]
Just the art mode! Like it’s supposed to work :)
‘node script1.js TVIP’

**Comment by JordanPatterson** [comment]
Script 1
`Jordans-Mac-mini:TV jordanpatterson$ node script1.js 192.168.1.3
IP of TV is: 192.168.1.3
message 14:11:422 {"event":"ms.channel.unauthorized"}
error { RangeError: Invalid WebSocket frame: invalid status code 1005
    at Receiver.controlMessage (/Users/jordanpatterson/node_modules/ws/lib/receiver.js:449:18)
    at Receiver.getData (/Users/jordanpatterson/node_modules/ws/lib/receiver.js:335:42)
    at Receiver.startLoop (/Users/jordanpatterson/node_modules/ws/lib/receiver.js:138:22)
    at Receiver._write (/Users/jordanpatterson/node_modules/ws/lib/receiver.js:74:10)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Receiver.Writable.write (_stream_writable.js:299:11)
    at Socket.socketOnData (/Users/jordanpatterson/node_modules/ws/lib/websocket.js:871:35)
    at Socket.emit (events.js:188:13)
    at addChunk (_stream_readable.js:288:12) [Symbol(status-code)]: 1002 }
close
`

**Comment by tavicu** [comment]
My bad! I have updated the scripts :)

**Comment by codyc1515** [comment]
Hello all. Sorry for the delay. Let me know if you need help with anything else.

pi@raspberrypi:~ $ node script1.js samsung.local
IP of TV is: samsung.local
message 47:9:251 {"data":{"clients":[{"attributes":{"name":null},"connectTime":1558789977544,"deviceName":"Smart Device","id":"849324e8-6783-4a1f-8c9f-42bc26b4d9","isHost":true},{"attributes":{"name":"RnJhbWUgVGVzdA=="},"connectTime":1559206029025,"deviceName":"RnJhbWUgVGVzdA==","id":"68fcee8d-625f-40de-9a71-a9799f969615","isHost":false}],"id":"68fcee8d-625f-40de-9a71-a9799f969615"},"event":"ms.channel.connect"}
message 47:9:256 {"data":{},"event":"ms.channel.ready"}
message 47:11:301 {"data":"{\"id\":\"30852acd-1b7d-4496-8bef-53e1178fa839\",\"event\":\"artmode_status\",\"value\":\"off\",\"target_client_id\":\"68fcee8d-625f-40de-9a71-a9799f969615\"}","event":"d2d_service_message","from":"849324e8-6783-4a1f-8c9f-42bc26b4d9"}
close

pi@raspberrypi:~ $ node script2.js samsung.local
IP of TV is: samsung.local
message 48:26:765 {"data":{"clients":[{"attributes":{"name":null},"connectTime":1558789977544,"deviceName":"Smart Device","id":"849324e8-6783-4a1f-8c9f-42bc26b4d9","isHost":true},{"attributes":{"name":"RnJhbWUgVGVzdA=="},"connectTime":1559206106553,"deviceName":"RnJhbWUgVGVzdA==","id":"d6aa5a32-b6bb-497e-acea-3b967cc96cd","isHost":false}],"id":"d6aa5a32-b6bb-497e-acea-3b967cc96cd"},"event":"ms.channel.connect"}
message 48:26:771 {"data":{},"event":"ms.channel.ready"}
message 48:28:782 {"data":"{\"id\":\"545fc0c1-bd9b-48f5-8444-02f9c519aaec\",\"event\":\"art_mode_changed\",\"value\":\"on\"}","event":"d2d_service_message","from":"849324e8-6783-4a1f-8c9f-42bc26b4d9"}
close

pi@raspberrypi:~ $ node script3.js samsung.local
IP of TV is: samsung.local
message 49:14:984 {"data":{"clients":[{"attributes":{"name":null},"connectTime":1558789977544,"deviceName":"Smart Device","id":"849324e8-6783-4a1f-8c9f-42bc26b4d9","isHost":true},{"attributes":{"name":"RnJhbWUgVGVzdA=="},"connectTime":1559206154742,"deviceName":"RnJhbWUgVGVzdA==","id":"9ba35813-a4f6-46da-8463-d157224c9bb2","isHost":false}],"id":"9ba35813-a4f6-46da-8463-d157224c9bb2"},"event":"ms.channel.connect"}
message 49:14:989 {"data":{},"event":"ms.channel.ready"}
message 49:17:15 {"data":"{\"id\":\"545fc0c1-bd9b-48f5-8444-02f9c519aaec\",\"event\":\"art_mode_changed\",\"value\":\"off\"}","event":"d2d_service_message","from":"849324e8-6783-4a1f-8c9f-42bc26b4d9"}
message 49:18:990 {"data":"{\"event\":\"art_mode_changed\",\"status\":\"off\"}","event":"d2d_service_message","from":"849324e8-6783-4a1f-8c9f-42bc26b4d9"}
close

pi@raspberrypi:~ $ node script4.js samsung.local
IP of TV is: samsung.local
message 50:4:706 {"data":{"clients":[{"attributes":{"name":null},"connectTime":1558789977544,"deviceName":"Smart Device","id":"849324e8-6783-4a1f-8c9f-42bc26b4d9","isHost":true},{"attributes":{"name":"RnJhbWUgVGVzdA=="},"connectTime":1559206204497,"deviceName":"RnJhbWUgVGVzdA==","id":"db6aa4b9-208c-4e5-bff1-def6a19125c","isHost":false}],"id":"db6aa4b9-208c-4e5-bff1-def6a19125c"},"event":"ms.channel.connect"}
message 50:4:711 {"data":{},"event":"ms.channel.ready"}
From remote set TV to Art mode OFF (turn tv OFF)
message 50:14:708 {"data":"{\"event\":\"art_mode_changed\",\"status\":\"on\"}","event":"d2d_service_message","from":"849324e8-6783-4a1f-8c9f-42bc26b4d9"}
From remote set TV to Art mode ON (turn tv ON)
message 50:19:296 {"data":"{\"event\":\"art_mode_changed\",\"status\":\"off\"}","event":"d2d_service_message","from":"849324e8-6783-4a1f-8c9f-42bc26b4d9"}
From remote set TV to Art mode OFF (turn tv OFF)
message 50:27:891 {"data":"{\"event\":\"art_mode_changed\",\"status\":\"on\"}","event":"d2d_service_message","from":"849324e8-6783-4a1f-8c9f-42bc26b4d9"}
close

**Comment by tavicu** [comment]
Awesome! Now i can map them :) Thanks

**Comment by tavicu** [comment]
@codyc1515 can you also help me with something. I don't think the `id` is required. Can you try for example the first script but remove the `id` from parameters?

script1.js -> line 43

So it will be: 
```
        send({
            request: 'get_artmode_status'
        });
```

**Comment by codyc1515** [comment]
Made the change. Looks like it's not required.

pi@raspberrypi:~ $ node script1.js samsung.local
IP of TV is: samsung.local
message 54:26:154 {"data":{"clients":[{"attributes":{"name":null},"connectTime":1558789977544,"deviceName":"Smart Device","id":"849324e8-6783-4a1f-8c9f-42bc26b4d9","isHost":true},{"attributes":{"name":"RnJhbWUgVGVzdA=="},"connectTime":1559210065833,"deviceName":"RnJhbWUgVGVzdA==","id":"76247431-faf9-4778-9fcd-ee25e539e8b","isHost":false}],"id":"76247431-faf9-4778-9fcd-ee25e539e8b"},"event":"ms.channel.connect"}
message 54:26:159 {"data":{},"event":"ms.channel.ready"}
message 54:28:183 {"data":"{\"id\":\"\",\"event\":\"artmode_status\",\"value\":\"off\",\"target_client_id\":\"76247431-faf9-4778-9fcd-ee25e539e8b\"}","event":"d2d_service_message","from":"849324e8-6783-4a1f-8c9f-42bc26b4d9"}
close

**Comment by tavicu** [comment]
Awesome :)

**Comment by codyc1515** [comment]
Hey Tavicu, any update on this one or some way that I can help?

**Comment by tavicu** [comment]
Hei! Sorry for the delay but i don’t have too much free time :) in one month i will have mt wedding :p

I will try to have a beta version next week!

**Comment by codyc1515** [comment]
Very cool. Good luck for the wedding! :)

**Comment by mauricelumiere** [comment]
Hello @tavicu,

Hope your wedding was great? 
I was wondering, how the status of the Frame support is?

I am using a Frame TV and Homebridge, would be great if this would work better with ArtMode.

Greeting Maurice

**Comment by senorshaun** [comment]
So I have been messing with this plugin for a while. Where I think it gets tricky is used case.
Personally, when I turn off the TV, I want it to turn off (HDMI CEC does that for me so yay). But what I like is when I show up home, for the TV to turn on and switch to art mode. So I updated the _turnOff call in remote.js to hold KEY_POWER for 3 seconds which actually turns it off. Then I added in an input that is simply KEY_POWER. Is this good, well, no it isn't because I'm not actually doing any checking. But it does mean that I can automate for my own personal plugin. 

If you need any help writing code, or if you at least have a roadmap, maybe I can help out tweaking some.

**Comment by tavicu** [comment]
@mauricelumiere thank you for asking. Unfortunately (for you) my wedding is in August and after that i will leave in honey moon!

I am working on a feature to keep an open connection as long as the TV is on. This will allow me to implement the frame tv functionality easier.

But i don't have an estimation when it will be ready. I am very busy with wedding preparations, dancing lessons and many others :D

**Comment by mauricelumiere** [comment]
So I wish you a beautiful and lovely wedding! Looking forward to hearing from you :)

**Comment by mauricelumiere** [comment]
@tavicu how are you ? Hopefully everything is great. Could you tell if you are able to follow up this topic ? Can i help with anything?

**Comment by arnowillig** [comment]
@tavicu Any progress on this matter? 
On running your script1, I get:
{"data":"{\"id\":\"30852acd-1b7d-4496-8bef-53e1178fa839\",\"event\":\"artmode_status\",\"value\":\"on\",\"target_client_id\":\"b3f2991f-cebc-435-8042-eeffffbc84f\"}","event":"d2d_service_message","from":"c8386846-1f74-47bd-a5c3-984b3757372c"}

"value" changes to "off", when art mode is off. 
When the TV is completely off, the network is down after a few seconds.

My tv is on art mode most of the time, but I really would like to create a HomeKit scene which exits art mode and sets some lights to the right brightness. 


With the current version there is still the problem that the TV is detected as "on", even if it is in art mode. By turning it "off" it will finish art mode and be "on". 
If I wait another few seconds it will be displayed as on again and "off" sets it into art mode.
Conclusion: We only need the on/off detection be aware of the art mode.

**Comment by mauricelumiere** [comment]
Would be awesome if we could be aware of the state check. Tell me if I could help with something.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tavicu** [comment]
No update here! Unfortunately my time is very limited until the end of November!

I already have all the endpoints for frame tv and made a socket server for developing/testing :)

All i need is time ... if anybody have some ... :))

**Comment by mauricelumiere** [comment]
Do you have any news ?

**Comment by mrMiimo** [comment]
Hi everyone, news?

**Comment by JordanPatterson** [comment]
I am still super interested in this update. I really hope that you have some time to continue development of this plugin.

**Comment by xaalisart** [comment]
I'm really interested in this Method !

**Comment by mrMiimo** [comment]
Do you have any news ?

**Comment by mmarras** [comment]
Also interested, what can be done to help?

**Comment by mauricelumiere** [comment]
So in the actual Beta of OpenHAB, the Samsung Thing supports The Frame. Maybe there are Resources helpful for development ? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Nicode70** [comment]
I would live to see some update on this request. Just let me know if i can help.

**Comment by Ghitafjorback** [comment]
Man, this update would be so cool. Any news on this?

**Comment by mrMiimo** [comment]
@tavicu there is any chance with "frametv" method? Thanks a lot, stay safe ...

**Comment by funkyremi** [comment]
Hello @tavicu :-) I have a Samsung The Frame TV. Can I help you with this development?

**Comment by zmoss** [comment]
Hi @tavicu, happy to help as well! Hope all is well and you are staying safe and healthy.

**Comment by soulcook** [comment]
I’m also very interested in this, and more than happy to test code on my Frame TV

**Comment by pwkrueger** [comment]
My 2019 Frame TV is playing nicely with Homebridge. I followed the directions in the thread below to get toggle between art and TV and also power on-off working: https://github.com/tavicu/homebridge-samsung-tizen/issues/215.

**Comment by swebdesign** [comment]
any update, no more time?

**Comment by pwkrueger** [comment]
As noted earlier, I just followed the directions in the thread below. It’s not a complete remote, but I can power on/off, and also toggle between art and tv modes.

https://github.com/tavicu/homebridge-samsung-tizen/issues/215

**Comment by Stetocasa** [comment]
Awaiting the official update of the plugin I solved by Samsung SmartThings plugin introducing a switch to turn on/off the tv.
Created and automation at night when I switch off the Tizens TV plugin, also automatically the switch turn off really the tv image

**Comment by jamesalmeida** [comment]
Any updates on this? I have a Frame TV I'd like to use with this.

**Comment by JannoMontano** [comment]
> I have started by creating a local websocket server which will respond like TV.
> Also i have created 4 scripts that someone with a Frame TV needs to run (@codyc1515 maybe 👍)
> 
> Scripts are here: https://gist.github.com/tavicu/5877d6c30a9166892e871b1cdae2b444
> 
> * Script 1 -> Turn the TV ON then run the script `node script1.js TV_IP`
> * Script 2 -> Turn the TV OFF then run the script `node script2.js TV_IP`
> * Script 3 -> Make sure TV is OFF then run the script `node script3.js TV_IP`
> * Script 4 -> Make sure TV is ON then run the script and follow the request from console (turning on and off the tv from remote control) `node script4.js TV_IP`
> 
> Once i have the console output of these 4 scripts i can map my local server like a frame tv.

Hello everyone,

Excuse my ignorance, but how can I run the scripts?

I tried to copy the files to the hoobs machine and then run from ssh but the terminal tells me this:

```
/home/hoobs/script1.js: line 1: let: =: syntax error: expected operand (error token is "=")
/home/hoobs/script1.js: line 3: syntax error near unexpected token `` 'TV IP is:' '
/home/hoobs/script1.js: line 3: `console.log ('The TV's IP is:' + 192.168.0.11); '

```

Obviously I am doing something wrong because I'm very noob in this things.

Can you help me please?

Sorry about my english, I am noob on this too jajaja.

Greetings

**Comment by JannoMontano** [comment]
> > I have started by creating a local websocket server which will respond like TV.
> > Also i have created 4 scripts that someone with a Frame TV needs to run (@codyc1515 maybe 👍)
> > Scripts are here: https://gist.github.com/tavicu/5877d6c30a9166892e871b1cdae2b444
> > 
> > * Script 1 -> Turn the TV ON then run the script `node script1.js TV_IP`
> > * Script 2 -> Turn the TV OFF then run the script `node script2.js TV_IP`
> > * Script 3 -> Make sure TV is OFF then run the script `node script3.js TV_IP`
> > * Script 4 -> Make sure TV is ON then run the script and follow the request from console (turning on and off the tv from remote control) `node script4.js TV_IP`
> > 
> > Once i have the console output of these 4 scripts i can map my local server like a frame tv.
> 
> Hello everyone,
> 
> Excuse my ignorance, but how can I run the scripts?
> 
> I tried to copy the files to the hoobs machine and then run from ssh but the terminal tells me this:
> 
> ```
> /home/hoobs/script1.js: line 1: let: =: syntax error: expected operand (error token is "=")
> /home/hoobs/script1.js: line 3: syntax error near unexpected token `` 'TV IP is:' '
> /home/hoobs/script1.js: line 3: `console.log ('The TV's IP is:' + 192.168.0.11); '
> ```
> 
> Obviously I am doing something wrong because I'm very noob in this things.
> 
> Can you help me please?
> 
> Sorry about my english, I am noob on this too jajaja.
> 
> Greetings

I could already run the scripts. THANKS! :)

**Comment by jackklink** [comment]
Hey just chiming in here as a FrameTV owner. Happy to help with this and very interested in figuring out Art Mode control with this application.

**Comment by tavicu** [comment]
Hi. With the recent updates on the plugin it allows me to implement Frame TV support.
I will need your help on finding answers on how Frame TV works in different scenarios since i don't have a tv with frame support.

If you want this implemented please help me over here: https://github.com/tavicu/homebridge-samsung-tizen/issues/318

**Pull request closed without merging**
