### PR TITLE
HB 2.0 beta fix

### PR DESCRIPTION
**Pull request by traviswparker**
replace hap.Accessory.Categories with hap.Categories and Characteristic.getValue() with .value

### CODE REVIEW

**Comment by tavicu** [comment]
This won't work. It fixes the "errors" but breaks functionality :)

**Comment by traviswparker** [comment]
Does it? HAP-nodeJS deprecated .getValue() as HomeKit is supposed to be refreshing .value.
Testing on HB 2.0, when I turn the TV on and off with the remote, the on/off state does change within the polling interval. Input selection works as does the control center remote.

**Comment by tavicu** [comment]
That function is to maintain all accessories synchronised. Turning off the main accessory, trigger an event to all switches to update the value right then.

On your PR, that function does nothing now :)

**Comment by traviswparker** [comment]
Well that’s annoying. Seems HAP-nodejs doesn’t provide a replacement for .getValue() From the API you can only get the current .value, so the on get function will only be called when HomeKit refreshes the state of the switches. Which it will do, but not immediately.If you’re working on HB 2 compatibility I’ll let you figure out a way to sync them. My experience with Homebridge plugin development is very limited.  On Aug 31, 2024, at 14:39, Octavian Ruda ***@***.***> wrote:﻿
That function is to maintain all accessories synchronised. Turning off the main accessory, trigger an event to all switches to update the value right then.
On your PR, that function does nothing now :)

**Pull request closed without merging**
